---
title:
output: html_document
---
<br><br><br>
<h1 align="center"><b>Modelo predictor de carros registrados en el RUNT.</b><hr><br><br></h1>

<h2 align="center"><b>Asignatura:</b></h2>
<h3 align="center">Técnicas de aprendizaje estadístico</h3>
<h3 align="center">Universidad Nacional de Colombia</h3>
<h3 align="center">Sede Medellín</h3>
<h3 align="center">Facultad de minas</h3>
<h3 align="center">2018-2<br><br></h3>

<h2 align="center"><b>Profesor:</b></h2>
<h3 align="center">Juan David Ospina Arango<br><br></h3>

<h2 align="center"><b>Hecho por:</b></h2>
<h3 align="center">Santiago Restrepo Álvarez</h3>
<h3 align="center">Mateo Zuluaga Giraldo</h3>
<h3 align="center">Sebastián Ramírez Tamayo</h3>
<h3 align="center">David Ossa Saldarriaga</h3>
<h3 align="center">Daniel Restrepo Mejía<hr><br><br><br></h3>

<h3><b>Introducción:</b></h3>
<p style = "font-size:20px" align="justify">
El siguiente trabajo gira en torno a crear un modelo predictivo de los automóviles registrados en el RUNT. ¿Cómo se logrará esto?: Más adelante veremos cómo a partir de un archivo que contiene el número de automóviles registrados diariamente en el RUNT desde 2012 hasta 2017, se puede "entrenar" un modelo para predecir los automóviles que se registrarán en un futuro.
</p><hr>


<h3><b>Entendimiento inicial:</b></h3>
<p style = "font-size:20px" align="justify">
Todo automóvil que se quiera poner en circulación en el país, debe antes ser registrado en el Registro Único Nacional de Transito(RUNT), con el fin de determinar la propiedad, características y situación jurídica de los vehículos automotores terrestres, este registro se lleva a cabo en los días hábiles y permite principalmente tener un registro completo de todos los automóviles terrestres que circulan sobre el territorio nacional. El RUNT permite conocer las fichas técnicas de homologación, emisiones de gases, entre otros datos de interés.
A continuación en el análisis técnico se verá detalladamente el procedimiento empleado para construir el modelo.
</p><hr>

<h3><b>Análisis técnico</b></h3>
<p style = "font-size:20px" align="justify">
Después de esta breve contextualización, se dará inicio a la explicación del cómo se construyó el proyecto; inicialmente se nos proporcionó un único archivo plano que contenía todos los registros de los automóviles registrados diariamente en el RUNT, el archivo contiene dos columnas, una de fecha y otra de número de autos registrados, y tiene una fila por cada día comprendido entre el primero(1) de Enero de 2012 y el treinta y uno(31) de Diciembre de 2017, el principal requisito del modelo es que sea entrenado con los datos de 2012 hasta 2016 y usar los datos de 2017 como validación y posteriormente predecir todo el primer semestre del 2018, cabe aclarar que no tenemos los datos reales del 2018, estos sólo los tiene el profesor.
Como sólo se tiene una variable, es necesario buscar por cuenta propia otras variables de las que podamos descargar sus registros en este lapso de tiempo y que estas variables mejoren la predicción del modelo; se partió de variables relacionadas con el crecimiento de la economía nacional cómo punto de partida. Las variables que inicialmente elegimos como candidatas para estar en el modelo cómo variables independientes son las siguientes:
</p><hr>
<ul style = "font-size:20px">
  <li>Mes
  <li>Día del mes
  <li>Día de la semana
  <li>Año
  <li>Tasa de empleo
  <li>Tasa de desempleo
  <li>Índice de precio al consumidor
  <li>Precio promedio de el barril de petróleo BRENT
  <li>Salario mínimo
  <li>DTF
  <li>Índice de confianza del consumidor
</ul>

<p style = "font-size:20px" align="justify">
***Acá va la explicación de cada variable***
</p><hr>

<h3><b>Enfoque</b></h3>
<p style = "font-size:20px" align="justify">
Después de todo este esfuerzo para construir este modelo que acabamos de ver, surgirá la pregunta ¿para qué todo esto? pues bueno, el proyecto podría no tener un enfoque único, ya que este modelo podría ser de mucha utilidad para el estado, o empresas privadas, a continuación veremos tres ejemplos prácticos.<br>
En primer lugar y el ejemplo más trivial estaría en la contratación del personal, ya que en número de registros de vehículos en un día, se traduce en personas haciendo fila, así que este modelo serviría para hacer una contratación dinámica, es decir que se contrate más personal, en los meses del año en los que más autos se registran para agilizar la atención y así mismo contratar menos personal en los meses con menos registros, para así ahorar recursos.<br>
Como segundo ejemplo, está la infraestructura vial y políticas de movilidad, ya que el modelo le serviría al estado para predecir el crecimiento del parque automotor, para implementar políticas de movilidad o construir infraestructura.<br>
Como último ejemplo, tenemos al seector privado, especificamente a las compañías que fabrican y venden autos, ya que estas, sabiendo la porción de mercado que tienen frente a la competencia, antes de inundar el mercado con más autos de los que van a vender, podrían predecir estas cifras, para no incurrir en perdidas por tenes demasiadas existencias de vehículos en venta, también les puede servir antes de implementar políticas de expansión.
</p><hr>

<h3><b>Referencias:</b></h3>
<p style = "font-size:20px" align="justify">
1. <a href = "https://www.runt.com.co/registros-runt/rna"> Página del RUNT </a>
2. <a href = "https://www.fedesarrollo.org.co/sites/default/files/encuestas_documentos/historico_indice_de_confianza_del_consumidor_eoc.pdf"> Indice de confianza del consumidor  </a>
</p><br>

<p style = "font-size:20px" align="justify">
Todo el proyecto fue desarrollado con el lenguaje de programación open-source R.<br>
R Core Team (2018). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/. <br>
Y se usaron los siguientes paquetes:
<ul style = "font-size:17px">
  <li><b>dplyr</b><br>Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2018). dplyr: A Grammar of Data Manipulation. R package version 0.7.6.
  https://CRAN.R-project.org/package=dplyr
  <li><b>MASS</b><br>Venables, W. N. & Ripley, B. D. (2002) Modern Applied Statistics with S. Fourth Edition. Springer, New York. ISBN 0-387-95457-0
  <li><b>Hmisc</b><br>Frank E Harrell Jr, with contributions from Charles Dupont and many others. (2018). Hmisc: Harrell Miscellaneous. R package version 4.1-1.
  https://CRAN.R-project.org/package=Hmisc
  <li><b>lubridate</b><br>Garrett Grolemund, Hadley Wickham (2011). Dates and Times Made Easy with lubridate. Journal of Statistical Software, 40(3), 1-25. URL
  http://www.jstatsoft.org/v40/i03/.
  <li><b>xlsx</b><br>Adrian A. Dragulescu and Cole Arendt (2018). xlsx: Read, Write, Format
  Excel 2007 and Excel 97/2000/XP/2003 Files. R package version 0.6.1.
  https://CRAN.R-project.org/package=xlsx.
</ul>
</p><hr>




